### ISSUE TITLE
Arrange elections information nicely in a table

### ISSUE THREAD

**Issue by JenMysoc** [theyworkforyou/shineyoureye-sinatra#115] opened 2017-03-24 14:37 UTC
Currently the elections page shows the details in a free text format

![screen shot 2017-03-24 at 14 27 38](https://cloud.githubusercontent.com/assets/4170351/24298860/38d47b7a-109f-11e7-8af3-62c7461f2e9f.png)

But EiE would like this to be in a table similar to on the original site

![screen shot 2017-03-24 at 14 27 49](https://cloud.githubusercontent.com/assets/4170351/24298913/614541ca-109f-11e7-9ba8-5fc1bcfb868e.png)

**Comment by octopusinvitro** [comment] 2017-03-24 14:42
See also https://github.com/theyworkforyou/shineyoureye-sinatra/issues/67

**Comment by mhl** [comment] 2017-03-27 11:22
Closing as a duplicate of #67

**Closed by mhl** 2017-03-27 11:22 UTC
Labels: Difficulty 3, EiEFeedback
